// *** Apocalypse Design Scripting System v1.0 ***
// Object script auto-created by Turbo's MAX-plugin
// Design is simply all...

  mesh "Plane22" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane22" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane22, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane21" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane21" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane21, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane20" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane20" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane20, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane19" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane19" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane19, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane18" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane18" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane18, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane17" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane17" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane17, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane16" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane16" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane16, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane15" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane15" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane15, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane13" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane13" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane13, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane12" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane12" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane12, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane11" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane11" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane11, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane10" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane10" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane10, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane09" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane09" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane09, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane08" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane08" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane08, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane07" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane07" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane07, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane06" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane06" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane06, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane05" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane05" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane05, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane04" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane04" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane04, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane03" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane03" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane03, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane02" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane02" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane02, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane01" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane14" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane14" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane14, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane24" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane24" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane24, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane25" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane25" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane25, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane26" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane26" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane26, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane27" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane27" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane27, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane28" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane28" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane28, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane29" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane29" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane29, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane30" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane30" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane30, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane31" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane31" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane31, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane32" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane32" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane32, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane33" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane33" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane33, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane34" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane34" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane34, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane35" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane35" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane35, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane36" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane36" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane36, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane37" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane37" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane37, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane38" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane38" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane38, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane39" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane39" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane39, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane40" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane40" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane40, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane41" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane41" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane41, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane42" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane42" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane42, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane43" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane43" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane43, 0, 99999.99";
    static_vertex="YES";
  }

