// *** Apocalypse Design Scripting System v1.0 ***
// Particle systems script auto-created by Turbo's MAX-plugin
// Design is simply all...

  particle "Snow01"
  {
     father="NONE";
     texture="bubble.jpg";
     emitter_width="200";
     emitter_height="200";
     faded_particles="0.4";
     max_particles="250";
     start_time="0";
     end_time="200";
     life="70";
     speed="20.000000";
     variation="2.000000";
     size_attenuation="0.4, 1.0, 0.08, 0";
  }

