// *** Apocalypse Design Scripting System v1.0 ***
// Object script auto-created by Turbo's MAX-plugin
// Design is simply all...

  mesh "Sphere02" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere02" 
  {
    type="SOLID";
    father="NONE";
    material="2 - Default";
    lod="Sphere02, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere01" 
  {
    type="SOLID";
    father="Sphere02";
    material="1 - Default";
    lod="Sphere01, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere04" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere04" 
  {
    type="SOLID";
    father="NONE";
    material="2 - Default";
    lod="Sphere04, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere03" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere03" 
  {
    type="SOLID";
    father="Sphere04";
    material="1 - Default";
    lod="Sphere03, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere06" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere06" 
  {
    type="SOLID";
    father="NONE";
    material="2 - Default";
    lod="Sphere06, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere05" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere05" 
  {
    type="SOLID";
    father="Sphere06";
    material="1 - Default";
    lod="Sphere05, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere08" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere08" 
  {
    type="SOLID";
    father="NONE";
    material="2 - Default";
    lod="Sphere08, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere07" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere07" 
  {
    type="SOLID";
    father="Sphere08";
    material="1 - Default";
    lod="Sphere07, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere09" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere09" 
  {
    type="SOLID";
    father="NONE";
    material="2 - Default";
    lod="Sphere09, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere10" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere10" 
  {
    type="SOLID";
    father="Sphere09";
    material="1 - Default";
    lod="Sphere10, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere11" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere11" 
  {
    type="SOLID";
    father="NONE";
    material="2 - Default";
    lod="Sphere11, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere12" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere12" 
  {
    type="SOLID";
    father="Sphere11";
    material="1 - Default";
    lod="Sphere12, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere14" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere14" 
  {
    type="SOLID";
    father="NONE";
    material="2 - Default";
    lod="Sphere14, 0, 99999.99";
    static_vertex="NO";
  }

  mesh "Sphere13" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Sphere13" 
  {
    type="SOLID";
    father="Sphere14";
    material="1 - Default";
    lod="Sphere13, 0, 99999.99";
    static_vertex="NO";
  }

