// *** Apocalypse Design Scripting System v1.0 ***
// Particle systems script auto-created by Turbo's MAX-plugin
// Design is simply all...

  particle "Snow01"
  {
     father="NONE";
     texture="bubble.jpg";
     emitter_width="1000";
     emitter_height="500";
     faded_particles="OFF";
     max_particles="200";
     start_time="0";
     end_time="200";
     life="100";
     speed="10.000000";
     variation="2.000000";
     size_attenuation="1.2, 1.0, 0, 0.0015";
  }

