#define CV_WORLDVIEWPROJ_0 0
#define CV_WORLDVIEWPROJ_1 1
#define CV_WORLDVIEWPROJ_2 2
#define CV_WORLDVIEWPROJ_3 3

#define CV_WORLD_0 4
#define CV_WORLD_1 5
#define CV_WORLD_2 6
#define CV_WORLD_3 7

#define CV_MAP1UVMATRIX_0 8
#define CV_MAP1UVMATRIX_1 9
#define CV_MAP1UVMATRIX_2 10
#define CV_MAP1UVMATRIX_3 11

#define CV_MAP2UVMATRIX_0 12
#define CV_MAP2UVMATRIX_1 13
#define CV_MAP2UVMATRIX_2 14
#define CV_MAP2UVMATRIX_3 15

#define CV_LIGHT_COLOR 16
#define CV_LIGHT_DIRECTION 17
#define CV_LIGHT_POSITION 18
#define CV_LIGHT_OBJECT_POSITION 19
#define CV_LIGHT_OBJECT_DIRECTION 20

#define CV_SILOUETTE_SCALING 21
#define CV_MATERIAL_ALPHA 22

#define CV_ZERO 25
#define CV_ONE 26
#define CV_HALF 27

