// *** Apocalypse Design Scripting System v1.0 ***
// Object script auto-created by Turbo's MAX-plugin
// Design is simply all...

  mesh "Rectangle22" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle22" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle22, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra22" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra22" 
  {
    type="SOLID";
    father="Rectangle22";
    material="Material #49";
    lod="Hedra22, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle23" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle23" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle23, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra01" 
  {
    type="SOLID";
    father="Rectangle23";
    material="Material #49";
    lod="Hedra01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle24" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle24" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle24, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra24" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra24" 
  {
    type="SOLID";
    father="Rectangle24";
    material="Material #49";
    lod="Hedra24, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle25" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle25" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle25, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra02" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra02" 
  {
    type="SOLID";
    father="Rectangle25";
    material="Material #49";
    lod="Hedra02, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle26" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle26" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle26, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra27" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra27" 
  {
    type="SOLID";
    father="Rectangle26";
    material="Material #49";
    lod="Hedra27, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle27" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle27" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle27, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra25" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra25" 
  {
    type="SOLID";
    father="Rectangle27";
    material="Material #49";
    lod="Hedra25, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle28" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle28" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle28, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra28" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra28" 
  {
    type="SOLID";
    father="Rectangle28";
    material="Material #49";
    lod="Hedra28, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle29" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle29" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle29, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra26" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra26" 
  {
    type="SOLID";
    father="Rectangle29";
    material="Material #49";
    lod="Hedra26, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle30" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle30" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle30, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra29" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra29" 
  {
    type="SOLID";
    father="Rectangle30";
    material="Material #49";
    lod="Hedra29, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle31" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle31" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle31, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra30" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra30" 
  {
    type="SOLID";
    father="Rectangle31";
    material="Material #49";
    lod="Hedra30, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle32" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle32" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle32, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra31" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra31" 
  {
    type="SOLID";
    father="Rectangle32";
    material="Material #49";
    lod="Hedra31, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle33" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle33" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle33, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra36" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra36" 
  {
    type="SOLID";
    father="Rectangle33";
    material="Material #49";
    lod="Hedra36, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle34" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle34" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle34, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra33" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra33" 
  {
    type="SOLID";
    father="Rectangle34";
    material="Material #49";
    lod="Hedra33, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle35" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle35" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle35, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra34" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra34" 
  {
    type="SOLID";
    father="Rectangle35";
    material="Material #49";
    lod="Hedra34, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle36" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle36" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle36, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra35" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra35" 
  {
    type="SOLID";
    father="Rectangle36";
    material="Material #49";
    lod="Hedra35, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle37" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle37" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle37, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra32" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra32" 
  {
    type="SOLID";
    father="Rectangle37";
    material="Material #49";
    lod="Hedra32, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle38" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle38" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle38, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra37" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra37" 
  {
    type="SOLID";
    father="Rectangle38";
    material="Material #49";
    lod="Hedra37, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle39" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle39" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle39, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra38" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra38" 
  {
    type="SOLID";
    father="Rectangle39";
    material="Material #49";
    lod="Hedra38, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle40" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle40" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle40, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra39" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra39" 
  {
    type="SOLID";
    father="Rectangle40";
    material="Material #49";
    lod="Hedra39, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle41" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle41" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle41, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra40" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra40" 
  {
    type="SOLID";
    father="Rectangle41";
    material="Material #49";
    lod="Hedra40, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle42" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle42" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle42, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra41" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra41" 
  {
    type="SOLID";
    father="Rectangle42";
    material="Material #49";
    lod="Hedra41, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle43" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle43" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle43, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra42" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra42" 
  {
    type="SOLID";
    father="Rectangle43";
    material="Material #49";
    lod="Hedra42, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle44" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle44" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle44, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra43" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra43" 
  {
    type="SOLID";
    father="Rectangle44";
    material="Material #49";
    lod="Hedra43, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle45" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle45" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle45, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra44" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra44" 
  {
    type="SOLID";
    father="Rectangle45";
    material="Material #49";
    lod="Hedra44, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle46" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle46" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle46, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra45" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra45" 
  {
    type="SOLID";
    father="Rectangle46";
    material="Material #49";
    lod="Hedra45, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle47" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle47" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle47, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra46" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra46" 
  {
    type="SOLID";
    father="Rectangle47";
    material="Material #49";
    lod="Hedra46, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle48" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle48" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle48, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra47" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra47" 
  {
    type="SOLID";
    father="Rectangle48";
    material="Material #49";
    lod="Hedra47, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle49" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle49" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle49, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra48" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra48" 
  {
    type="SOLID";
    father="Rectangle49";
    material="Material #49";
    lod="Hedra48, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle50" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle50" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle50, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra49" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra49" 
  {
    type="SOLID";
    father="Rectangle50";
    material="Material #49";
    lod="Hedra49, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle51" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle51" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle51, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra50" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra50" 
  {
    type="SOLID";
    father="Rectangle51";
    material="Material #49";
    lod="Hedra50, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle52" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle52" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle52, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra51" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra51" 
  {
    type="SOLID";
    father="Rectangle52";
    material="Material #49";
    lod="Hedra51, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Rectangle53" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Rectangle53" 
  {
    type="SOLID";
    father="NONE";
    material="Material #49";
    lod="Rectangle53, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Hedra52" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Hedra52" 
  {
    type="SOLID";
    father="Rectangle53";
    material="Material #49";
    lod="Hedra52, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object" 
  {
    type="SOLID";
    father="NONE";
    material="Material #2";
    lod="object, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object4" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object4" 
  {
    type="SOLID";
    father="object";
    material="Material #3";
    lod="object4, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object12" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object12" 
  {
    type="SOLID";
    father="object";
    material="Material #2";
    lod="object12, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object11" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object11" 
  {
    type="SOLID";
    father="object";
    material="Material #2";
    lod="object11, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object9" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object9" 
  {
    type="SOLID";
    father="object";
    material="Material #2";
    lod="object9, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object10" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object10" 
  {
    type="SOLID";
    father="object";
    material="Material #2";
    lod="object10, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object6" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object6" 
  {
    type="SOLID";
    father="object";
    material="Material #2";
    lod="object6, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object5" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object5" 
  {
    type="SOLID";
    father="object";
    material="Material #2";
    lod="object5, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object2" 
  {
    type="SOLID";
    father="object";
    material="Material #2";
    lod="object2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object3" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object3" 
  {
    type="SOLID";
    father="object";
    material="Material #3";
    lod="object3, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object8" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object8" 
  {
    type="SOLID";
    father="object";
    material="Material #2";
    lod="object8, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object7" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object7" 
  {
    type="SOLID";
    father="object";
    material="Material #2";
    lod="object7, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "objectP2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "objectP2" 
  {
    type="SOLID";
    father="NONE";
    material="Material #3";
    lod="objectP2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object9P2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object9P2" 
  {
    type="SOLID";
    father="objectP2";
    material="Material #3";
    lod="object9P2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object10P2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object10P2" 
  {
    type="SOLID";
    father="objectP2";
    material="Material #3";
    lod="object10P2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object4P2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object4P2" 
  {
    type="SOLID";
    father="objectP2";
    material="Material #3";
    lod="object4P2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object3P2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object3P2" 
  {
    type="SOLID";
    father="objectP2";
    material="Material #3";
    lod="object3P2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object5P2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object5P2" 
  {
    type="SOLID";
    father="objectP2";
    material="Material #3";
    lod="object5P2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object6P2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object6P2" 
  {
    type="SOLID";
    father="objectP2";
    material="Material #3";
    lod="object6P2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object2P2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object2P2" 
  {
    type="SOLID";
    father="objectP2";
    material="Material #3";
    lod="object2P2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object8P2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object8P2" 
  {
    type="SOLID";
    father="objectP2";
    material="Material #3";
    lod="object8P2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "object7P2" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "object7P2" 
  {
    type="SOLID";
    father="objectP2";
    material="Material #3";
    lod="object7P2, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "terreno" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "terreno" 
  {
    type="SOLID";
    father="NONE";
    material="01 - Default";
    lod="terreno, 0, 99999.99";
    static_vertex="YES";
  }

