// *** Apocalypse Design Scripting System v1.0 ***
// Object script auto-created by Turbo's MAX-plugin
// Design is simply all...

  mesh "Plane01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane01" 
  {
    type="SOLID";
    father="NONE";
    material="8 - Default";
    lod="Plane01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane02" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane02" 
  {
    type="SOLID";
    father="NONE";
    material="3 - Default";
    lod="Plane02, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane03" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane03" 
  {
    type="SOLID";
    father="NONE";
    material="7 - Default";
    lod="Plane03, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane04" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane04" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Plane04, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane05" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane05" 
  {
    type="SOLID";
    father="NONE";
    material="2 - Default";
    lod="Plane05, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "E1_engine" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "E1_engine" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="E1_engine, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "N1_engine" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "N1_engine" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="N1_engine, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "G1-engine" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "G1-engine" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="G1-engine, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "I1-engine" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "I1-engine" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="I1-engine, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "N2-engine" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "N2-engine" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="N2-engine, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "E2-engine" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "E2-engine" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="E2-engine, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane06" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane06" 
  {
    type="SOLID";
    father="NONE";
    material="13 - Default";
    lod="Plane06, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "F1-fuel" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "F1-fuel" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="F1-fuel, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "U1-fuel" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "U1-fuel" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="U1-fuel, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "L1-fuel" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "L1-fuel" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="L1-fuel, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "E1-fuel" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "E1-fuel" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="E1-fuel, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "O1-noise" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "O1-noise" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="O1-noise, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "S1-noise" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "S1-noise" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="S1-noise, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "I1-noise" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "I1-noise" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="I1-noise, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "N1-noise" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "N1-noise" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="N1-noise, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "E1-noise" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "E1-noise" 
  {
    type="SOLID";
    father="NONE";
    material="9 - Default";
    lod="E1-noise, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane07" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane07" 
  {
    type="SOLID";
    father="NONE";
    material="14 - Default";
    lod="Plane07, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane08" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane08" 
  {
    type="SOLID";
    father="NONE";
    material="15 - Default";
    lod="Plane08, 0, 99999.99";
    static_vertex="YES";
  }

