// *** Apocalypse Design Scripting System v1.0 ***
// Object script auto-created by Turbo's MAX-plugin
// Design is simply all...

  mesh "Text01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text01" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text02" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text02" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text02, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text03" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text03" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text03, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text04" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text04" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text04, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text05" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text05" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text05, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text06" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text06" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text06, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text07" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text07" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text07, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text08" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text08" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text08, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text09" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text09" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text09, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text10" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text10" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text10, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text11" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text11" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text11, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Text12" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "Text12" 
  {
    type="SOLID";
    father="NONE";
    material="1 - Default";
    lod="Text12, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "MID01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "MID01" 
  {
    type="SOLID";
    father="NONE";
    material="NONE";
    lod="MID01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "TIPS01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "TIPS01" 
  {
    type="SOLID";
    father="NONE";
    material="NONE";
    lod="TIPS01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "SWIRLS01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 0, 0";
  }

  object "SWIRLS01" 
  {
    type="SOLID";
    father="NONE";
    material="NONE";
    lod="SWIRLS01, 0, 99999.99";
    static_vertex="YES";
  }

