// *** Apocalypse Design Scripting System v1.0 ***
// Object script auto-created by Turbo's MAX-plugin
// Design is simply all...

  mesh "Form01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Form01" 
  {
    type="SOLID";
    father="NONE";
    material="Material #34";
    lod="Form01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Form02" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Form02" 
  {
    type="SOLID";
    father="NONE";
    material="Material #34";
    lod="Form02, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Form03" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Form03" 
  {
    type="SOLID";
    father="NONE";
    material="Material #34";
    lod="Form03, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Capsule01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Capsule01" 
  {
    type="SOLID";
    father="NONE";
    material="Material #33";
    lod="Capsule01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Gengon01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Gengon01" 
  {
    type="SOLID";
    father="NONE";
    material="Material #33";
    lod="Gengon01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Gengon02" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Gengon02" 
  {
    type="SOLID";
    father="NONE";
    material="Material #34";
    lod="Gengon02, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Gengon03" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Gengon03" 
  {
    type="SOLID";
    father="NONE";
    material="Material #33";
    lod="Gengon03, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Gengon04" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Gengon04" 
  {
    type="SOLID";
    father="NONE";
    material="Material #39";
    lod="Gengon04, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Gengon05" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Gengon05" 
  {
    type="SOLID";
    father="NONE";
    material="Material #39";
    lod="Gengon05, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Gengon06" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Gengon06" 
  {
    type="SOLID";
    father="NONE";
    material="Material #39";
    lod="Gengon06, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Tube01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Tube01" 
  {
    type="SOLID";
    father="NONE";
    material="Material #39";
    lod="Tube01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane01" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane01" 
  {
    type="SOLID";
    father="NONE";
    material="Material #35";
    lod="Plane01, 0, 99999.99";
    static_vertex="YES";
  }

  mesh "Plane02" 
  {
    normalize="OFF";
    boundvolumes_depths="0, 1, 0";
  }

  object "Plane02" 
  {
    type="SOLID";
    father="NONE";
    material="Material #30";
    lod="Plane02, 0, 99999.99";
    static_vertex="YES";
  }

